

//Rohan Tankala, rtankala1, 122836166, Professor Blessing Ajiboye, WEB422




import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import jwt from 'jsonwebtoken'
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [message, setMessage] = useState('You are not logged in')
  // const [secret, setSecret] = useState('')

  async function submitForm() {
    const res = await fetch('api/login', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        username, password
      })
    })
    .then(t => t.json())

    const token = res.token

    if (token) {
      const json = jwt.decode(token)
      setMessage('Welcome ' + json.username + ' and you are ' + (json.admin ? '' : 'not') + ' an admin');
      localStorage.setItem('token', token)
    } else {
      setMessage('Login failed')
    }
  }

  function handleLogout() {
    localStorage.removeItem('token');
    setMessage('You are not logged in');
    setUsername('');
    setPassword('');
  }

  return (
    <>
      <h1>{message}</h1>
      {/* <h1>Secret: {secret}</h1> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <form>
          <input type ="text" name="username" value={username} onChange={(e) => setUsername(e.target.value)}/>
          <br/>
          <input type ="password" name='password' value={password} onChange={(e) => setPassword(e.target.value)}/>
          <br/>
          <input type ="button" value="Login" onClick={submitForm}/>
          <input type ="button" value="Logout" onClick={handleLogout}/>
        </form>
      </main>
    </>
  )
}
